region                   = "asia-southeast1"
env_prefix               = "hc-demo"
zone                     = "asia-southeast1-a"
gpu_machine_type         = "g2-standard-12"
gpu_accelerator_type     = "nvidia-l4"
node_locations           = ["asia-southeast1-a", "asia-southeast1-b", "asia-southeast1-c"]
app_version              = "v1.10"
model_name               = "google-gemma-4-E4B-it"
model_subdir             = "gemma-4-e4b-it-weights"
model_served_name        = "gemma-4-E4B-it"
model_hf_repo            = "google/gemma-4-E4B-it"
vllm_image               = "vllm/vllm-openai:gemma4"
vllm_extra_args          = ["--enable-auto-tool-choice", "--tool-call-parser", "gemma4", "--gpu-memory-utilization", "0.9"]
use_gemini_api           = true
enable_vllm              = false
gemini_model_name        = "gemini-2.5-flash"
vllm_hpa_target_cpu      = 50
enable_inference_gateway = false
cloud_run_port           = 8080
cloud_run_active         = true
app_active               = true
monitoring_active        = true
create_alerts            = false
